trigger:
- main

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the solution'
  jobs:
    - template: template-build.yml
      parameters:
        appName: 'web'
        csproj: '**/web.csproj'

- stage: 'DeployDev'
  displayName: 'Deploy to Dev'
  condition: succeeded()
  jobs:
  - template: template-deploy.yml
    parameters:
      appName: 'web'
      resourceLocation: 'australiaeast'
      env: 'dev'
      envFullName: 'Development'
      variableGroupName: 'sample-dev'

- stage: 'DeployTest'
  displayName: 'Deploy to Test'
  condition: succeeded()
  dependsOn:
    - DeployDev
  jobs:
  - template: template-deploy.yml
    parameters:
      appName: 'web'
      resourceLocation: 'australiaeast'
      env: 'tst'
      envFullName: 'Test'
      variableGroupName: 'sample-tst'

- stage: 'DeployUat'
  displayName: 'Deploy to Uat'
  condition: succeeded()
  dependsOn:
    - DeployTest
  jobs:
  - template: template-deploy.yml
    parameters:
      appName: 'web'
      resourceLocation: 'australiaeast'
      env: 'uat'
      envFullName: 'UAT'
      variableGroupName: 'sample-uat'

- stage: 'DeployProd'
  displayName: 'Deploy to Prod'
  condition: succeeded()
  dependsOn:
    - DeployUat
  jobs:
  - template: template-deploy.yml
    parameters:
      appName: 'web'
      resourceLocation: 'australiaeast'
      env: 'prd'
      envFullName: 'Production'
      variableGroupName: 'sample-prd'
